create table if not exists public.posting_policy_tiers (
  id bigint generated by default as identity primary key,
  tier_name text not null unique,
  min_account_age_days integer not null default 0
    check (min_account_age_days >= 0),
  thread_limit_per_day integer not null
    check (thread_limit_per_day >= 0),
  reply_limit_per_day integer not null
    check (reply_limit_per_day >= 0),
  created_at timestamp with time zone not null default timezone('utc', now()),
  updated_at timestamp with time zone not null default timezone('utc', now())
);

create table if not exists public.posting_policy_activity_requirements (
  tier_id bigint primary key references public.posting_policy_tiers(id) on delete cascade,
  lookback_days integer not null
    check (lookback_days > 0),
  min_active_days integer not null
    check (min_active_days >= 0 and min_active_days <= lookback_days),
  created_at timestamp with time zone not null default timezone('utc', now()),
  updated_at timestamp with time zone not null default timezone('utc', now())
);

create table if not exists public.account_moderation_flags (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  is_posting_blocked boolean not null default true,
  reason text,
  flagged_by uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone not null default timezone('utc', now()),
  updated_at timestamp with time zone not null default timezone('utc', now())
);

create table if not exists public.account_daily_post_stats (
  user_id uuid not null references public.profiles(id) on delete cascade,
  activity_date date not null,
  thread_count integer not null default 0
    check (thread_count >= 0),
  reply_count integer not null default 0
    check (reply_count >= 0),
  created_at timestamp with time zone not null default timezone('utc', now()),
  updated_at timestamp with time zone not null default timezone('utc', now()),
  primary key (user_id, activity_date)
);

create index if not exists posting_policy_tiers_min_age_idx
  on public.posting_policy_tiers (min_account_age_days desc);

create index if not exists account_daily_post_stats_activity_date_idx
  on public.account_daily_post_stats (activity_date desc);

drop trigger if exists posting_policy_tiers_set_updated_at on public.posting_policy_tiers;
create trigger posting_policy_tiers_set_updated_at
before update on public.posting_policy_tiers
for each row
execute function public.set_updated_at();

drop trigger if exists posting_policy_activity_requirements_set_updated_at on public.posting_policy_activity_requirements;
create trigger posting_policy_activity_requirements_set_updated_at
before update on public.posting_policy_activity_requirements
for each row
execute function public.set_updated_at();

drop trigger if exists account_moderation_flags_set_updated_at on public.account_moderation_flags;
create trigger account_moderation_flags_set_updated_at
before update on public.account_moderation_flags
for each row
execute function public.set_updated_at();

drop trigger if exists account_daily_post_stats_set_updated_at on public.account_daily_post_stats;
create trigger account_daily_post_stats_set_updated_at
before update on public.account_daily_post_stats
for each row
execute function public.set_updated_at();

alter table public.posting_policy_tiers enable row level security;
alter table public.posting_policy_activity_requirements enable row level security;
alter table public.account_moderation_flags enable row level security;
alter table public.account_daily_post_stats enable row level security;

drop policy if exists posting_policy_tiers_authenticated_read on public.posting_policy_tiers;
create policy posting_policy_tiers_authenticated_read
on public.posting_policy_tiers
for select
to authenticated
using (true);

drop policy if exists posting_policy_activity_requirements_authenticated_read on public.posting_policy_activity_requirements;
create policy posting_policy_activity_requirements_authenticated_read
on public.posting_policy_activity_requirements
for select
to authenticated
using (true);

drop policy if exists account_daily_post_stats_self_read on public.account_daily_post_stats;
create policy account_daily_post_stats_self_read
on public.account_daily_post_stats
for select
to authenticated
using ((select auth.uid()) = user_id);

grant select on public.posting_policy_tiers to authenticated;
grant select on public.posting_policy_activity_requirements to authenticated;
grant select on public.account_daily_post_stats to authenticated;

create or replace function public.bump_account_daily_post_stats_on_post_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_activity_date date;
begin
  v_activity_date := timezone('utc', new.created_at)::date;

  insert into public.account_daily_post_stats (
    user_id,
    activity_date,
    thread_count,
    reply_count,
    created_at,
    updated_at
  )
  values (
    new.user_id,
    v_activity_date,
    case when new.reply_to_id is null then 1 else 0 end,
    case when new.reply_to_id is null then 0 else 1 end,
    timezone('utc', now()),
    timezone('utc', now())
  )
  on conflict (user_id, activity_date) do update
    set thread_count = public.account_daily_post_stats.thread_count +
        case when new.reply_to_id is null then 1 else 0 end,
        reply_count = public.account_daily_post_stats.reply_count +
        case when new.reply_to_id is null then 0 else 1 end,
        updated_at = timezone('utc', now());

  return new;
end;
$$;

drop trigger if exists posts_bump_daily_post_stats on public.posts;
create trigger posts_bump_daily_post_stats
after insert on public.posts
for each row
execute function public.bump_account_daily_post_stats_on_post_insert();

create or replace function public.publish_post_with_limits(
  p_event_tags text[] default '{}'::text[],
  p_content_hashes text[] default '{}'::text[],
  p_media_type text default 'text',
  p_caption text default null,
  p_latitude double precision default null,
  p_longitude double precision default null,
  p_preview_base64 text default null,
  p_preview_mime_type text default null,
  p_source_type text default 'firsthand',
  p_is_danger_mode boolean default false,
  p_is_virtual boolean default false,
  p_is_ai_generated boolean default false,
  p_is_text_only boolean default false,
  p_reply_to_id uuid default null,
  p_spot_name text default null,
  p_tags text[] default '{}'::text[],
  p_created_at timestamp with time zone default null
)
returns public.posts
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user_id uuid;
  v_now timestamp with time zone;
  v_today date;
  v_profile_created_at timestamp with time zone;
  v_account_age_days integer;
  v_event_tags text[];
  v_primary_event_tag text;
  v_tags text[];
  v_media_type text;
  v_source_type text;
  v_parent_post public.posts%rowtype;
  v_today_threads integer := 0;
  v_today_replies integer := 0;
  v_effective_tier_id bigint;
  v_effective_tier_name text;
  v_effective_thread_limit integer;
  v_effective_reply_limit integer;
  v_effective_lookback_days integer := 0;
  v_effective_min_active_days integer := 0;
  v_effective_active_days integer := 0;
  v_locked_tier_name text;
  v_locked_thread_limit integer;
  v_locked_reply_limit integer;
  v_locked_lookback_days integer := 0;
  v_locked_min_active_days integer := 0;
  v_locked_active_days integer := 0;
  v_candidate record;
  v_candidate_active_days integer;
  v_tag text;
  v_post public.posts%rowtype;
  v_denial_message text;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception using
      errcode = 'P0001',
      message = 'authenticated user required',
      detail = 'AUTH_REQUIRED',
      hint = 'Sign in again and retry.';
  end if;

  v_now := now();
  v_today := (v_now at time zone 'utc')::date;

  if exists (
    select 1
    from public.account_moderation_flags f
    where f.user_id = v_user_id
      and f.is_posting_blocked
  ) then
    select coalesce(nullif(btrim(reason), ''), 'This account is blocked from publishing due to spam or bot-like activity.')
      into v_denial_message
    from public.account_moderation_flags
    where user_id = v_user_id
      and is_posting_blocked
    limit 1;

    raise exception using
      errcode = 'P0001',
      message = 'posting blocked',
      detail = 'POSTING_BLOCKED',
      hint = v_denial_message;
  end if;

  select p.created_at
    into v_profile_created_at
  from public.profiles p
  where p.id = v_user_id
  limit 1;

  if v_profile_created_at is null then
    raise exception using
      errcode = 'P0001',
      message = 'profile missing for current user',
      detail = 'PROFILE_REQUIRED',
      hint = 'Refresh your session and try again.';
  end if;

  v_account_age_days := greatest(
    floor(extract(epoch from (v_now - v_profile_created_at)) / 86400)::integer,
    0
  );

  select coalesce(array_agg(tag order by first_position), '{}'::text[])
    into v_event_tags
  from (
    select
      min(item.ordinality) as first_position,
      lower(btrim(item.value)) as tag
    from unnest(coalesce(p_event_tags, '{}'::text[])) with ordinality as item(value, ordinality)
    where nullif(lower(btrim(item.value)), '') is not null
    group by lower(btrim(item.value))
  ) normalized_event_tags;

  select coalesce(array_agg(tag order by first_position), '{}'::text[])
    into v_tags
  from (
    select
      min(item.ordinality) as first_position,
      btrim(item.value) as tag
    from unnest(coalesce(p_tags, '{}'::text[])) with ordinality as item(value, ordinality)
    where nullif(btrim(item.value), '') is not null
    group by btrim(item.value)
  ) normalized_tags;

  if p_reply_to_id is not null then
    select p.*
      into v_parent_post
    from public.posts p
    where p.id = p_reply_to_id
      and p.deleted_at is null
    limit 1;

    if not found then
      raise exception using
        errcode = 'P0001',
        message = 'reply target not found',
        detail = 'REPLY_TARGET_NOT_FOUND',
        hint = 'The post you are replying to is unavailable.';
    end if;

    if cardinality(v_event_tags) = 0 then
      v_event_tags := coalesce(v_parent_post.event_tags, '{}'::text[]);
      if cardinality(v_event_tags) = 0 and v_parent_post.event_hashtag is not null then
        v_event_tags := array[v_parent_post.event_hashtag];
      end if;
    end if;
  end if;

  if cardinality(v_event_tags) = 0 and p_reply_to_id is null then
    raise exception using
      errcode = 'P0001',
      message = 'missing category tag',
      detail = 'MISSING_CATEGORY_TAG',
      hint = 'Add a category tag before posting a new thread.';
  end if;

  v_primary_event_tag := case
    when cardinality(v_event_tags) > 0 then v_event_tags[1]
    else null
  end;

  v_media_type := lower(btrim(coalesce(p_media_type, 'text')));
  if v_media_type not in ('image', 'video', 'text') then
    raise exception using
      errcode = 'P0001',
      message = 'invalid media type',
      detail = 'INVALID_MEDIA_TYPE',
      hint = 'Supported media types are image, video, or text.';
  end if;

  v_source_type := lower(btrim(coalesce(p_source_type, 'firsthand')));
  if v_source_type not in ('firsthand', 'secondhand') then
    raise exception using
      errcode = 'P0001',
      message = 'invalid source type',
      detail = 'INVALID_SOURCE_TYPE',
      hint = 'Supported source types are firsthand or secondhand.';
  end if;

  for v_candidate in
    select
      t.id,
      t.tier_name,
      t.min_account_age_days,
      t.thread_limit_per_day,
      t.reply_limit_per_day,
      coalesce(r.lookback_days, 0) as lookback_days,
      coalesce(r.min_active_days, 0) as min_active_days
    from public.posting_policy_tiers t
    left join public.posting_policy_activity_requirements r
      on r.tier_id = t.id
    order by t.min_account_age_days desc, t.id desc
  loop
    if v_candidate.min_account_age_days > v_account_age_days then
      continue;
    end if;

    v_candidate_active_days := 0;
    if v_candidate.min_active_days > 0 then
      select count(*)::integer
        into v_candidate_active_days
      from public.account_daily_post_stats s
      where s.user_id = v_user_id
        and s.activity_date >= (
          v_today - greatest(v_candidate.lookback_days - 1, 0)
        )
        and (s.thread_count + s.reply_count) > 0;
    end if;

    if v_candidate.min_active_days <= 0
       or v_candidate_active_days >= v_candidate.min_active_days then
      v_effective_tier_id := v_candidate.id;
      v_effective_tier_name := v_candidate.tier_name;
      v_effective_thread_limit := v_candidate.thread_limit_per_day;
      v_effective_reply_limit := v_candidate.reply_limit_per_day;
      v_effective_lookback_days := v_candidate.lookback_days;
      v_effective_min_active_days := v_candidate.min_active_days;
      v_effective_active_days := v_candidate_active_days;
      exit;
    end if;

    if v_locked_tier_name is null then
      v_locked_tier_name := v_candidate.tier_name;
      v_locked_thread_limit := v_candidate.thread_limit_per_day;
      v_locked_reply_limit := v_candidate.reply_limit_per_day;
      v_locked_lookback_days := v_candidate.lookback_days;
      v_locked_min_active_days := v_candidate.min_active_days;
      v_locked_active_days := v_candidate_active_days;
    end if;
  end loop;

  if v_effective_tier_id is null then
    raise exception using
      errcode = 'P0001',
      message = 'posting policy misconfigured',
      detail = 'POSTING_POLICY_MISSING',
      hint = 'No posting tier is available for this account.';
  end if;

  select
    coalesce(s.thread_count, 0),
    coalesce(s.reply_count, 0)
    into v_today_threads, v_today_replies
  from public.account_daily_post_stats s
  where s.user_id = v_user_id
    and s.activity_date = v_today
  limit 1;

  v_today_threads := coalesce(v_today_threads, 0);
  v_today_replies := coalesce(v_today_replies, 0);

  if p_reply_to_id is null and v_today_threads >= v_effective_thread_limit then
    if v_locked_tier_name is not null then
      v_denial_message := format(
        'Daily thread limit reached for your current activity level (%s/day). Be active on %s of the last %s UTC days to unlock %s/day.',
        v_effective_thread_limit,
        v_locked_min_active_days,
        v_locked_lookback_days,
        v_locked_thread_limit
      );
    else
      v_denial_message := format(
        'Daily thread limit reached (%s/day).',
        v_effective_thread_limit
      );
    end if;

    raise exception using
      errcode = 'P0001',
      message = 'daily thread limit reached',
      detail = 'THREAD_DAILY_LIMIT_REACHED',
      hint = v_denial_message;
  end if;

  if p_reply_to_id is not null and v_today_replies >= v_effective_reply_limit then
    if v_locked_tier_name is not null then
      v_denial_message := format(
        'Daily reply limit reached for your current activity level (%s/day). Be active on %s of the last %s UTC days to unlock %s/day.',
        v_effective_reply_limit,
        v_locked_min_active_days,
        v_locked_lookback_days,
        v_locked_reply_limit
      );
    else
      v_denial_message := format(
        'Daily reply limit reached (%s/day).',
        v_effective_reply_limit
      );
    end if;

    raise exception using
      errcode = 'P0001',
      message = 'daily reply limit reached',
      detail = 'REPLY_DAILY_LIMIT_REACHED',
      hint = v_denial_message;
  end if;

  foreach v_tag in array v_event_tags loop
    perform public.ensure_event_exists(
      v_tag,
      format('#%s', v_tag),
      null,
      p_latitude,
      p_longitude
    );
  end loop;

  insert into public.posts (
    event_hashtag,
    event_tags,
    user_id,
    content_hashes,
    media_type,
    caption,
    latitude,
    longitude,
    preview_base64,
    preview_mime_type,
    source_type,
    is_danger_mode,
    is_virtual,
    is_ai_generated,
    is_text_only,
    reply_to_id,
    spot_name,
    tags,
    created_at
  )
  values (
    v_primary_event_tag,
    v_event_tags,
    v_user_id,
    coalesce(p_content_hashes, '{}'::text[]),
    v_media_type,
    nullif(btrim(p_caption), ''),
    p_latitude,
    p_longitude,
    p_preview_base64,
    p_preview_mime_type,
    v_source_type,
    coalesce(p_is_danger_mode, false),
    coalesce(p_is_virtual, false),
    coalesce(p_is_ai_generated, false),
    coalesce(p_is_text_only, false),
    p_reply_to_id,
    nullif(btrim(p_spot_name), ''),
    v_tags,
    coalesce(p_created_at, v_now)
  )
  returning *
    into v_post;

  return v_post;
end;
$$;

grant execute on function public.publish_post_with_limits(
  text[],
  text[],
  text,
  text,
  double precision,
  double precision,
  text,
  text,
  text,
  boolean,
  boolean,
  boolean,
  boolean,
  uuid,
  text,
  text[],
  timestamp with time zone
) to authenticated;

insert into public.posting_policy_tiers (
  tier_name,
  min_account_age_days,
  thread_limit_per_day,
  reply_limit_per_day
)
values
  ('newcomer', 0, 2, 5),
  ('active', 3, 5, 12),
  ('established', 14, 10, 25)
on conflict (tier_name) do update
  set min_account_age_days = excluded.min_account_age_days,
      thread_limit_per_day = excluded.thread_limit_per_day,
      reply_limit_per_day = excluded.reply_limit_per_day,
      updated_at = timezone('utc', now());

insert into public.posting_policy_activity_requirements (
  tier_id,
  lookback_days,
  min_active_days
)
select id, 7, 2
from public.posting_policy_tiers
where tier_name = 'active'
on conflict (tier_id) do update
  set lookback_days = excluded.lookback_days,
      min_active_days = excluded.min_active_days,
      updated_at = timezone('utc', now());

insert into public.posting_policy_activity_requirements (
  tier_id,
  lookback_days,
  min_active_days
)
select id, 14, 5
from public.posting_policy_tiers
where tier_name = 'established'
on conflict (tier_id) do update
  set lookback_days = excluded.lookback_days,
      min_active_days = excluded.min_active_days,
      updated_at = timezone('utc', now());

delete from public.posting_policy_activity_requirements
where tier_id in (
  select id
  from public.posting_policy_tiers
  where tier_name = 'newcomer'
);

insert into public.account_daily_post_stats (
  user_id,
  activity_date,
  thread_count,
  reply_count,
  created_at,
  updated_at
)
select
  p.user_id,
  timezone('utc', p.created_at)::date as activity_date,
  count(*) filter (where p.reply_to_id is null)::integer as thread_count,
  count(*) filter (where p.reply_to_id is not null)::integer as reply_count,
  min(p.created_at) as created_at,
  timezone('utc', now()) as updated_at
from public.posts p
group by p.user_id, timezone('utc', p.created_at)::date
on conflict (user_id, activity_date) do update
  set thread_count = excluded.thread_count,
      reply_count = excluded.reply_count,
      updated_at = timezone('utc', now());

revoke insert, update on public.posts from authenticated;

drop policy if exists posts_owner_insert on public.posts;
drop policy if exists posts_owner_update on public.posts;
