#!/usr/bin/env bash
#
# Run terraform apply and export CDN outputs to a secrets env file.
#
# Usage:
#   scripts/01-terraform-apply-and-export.sh [output-file]
#
# Default output: scripts/cdn-secrets.env
#
# The env file is gitignored and can be fed directly to
# scripts/apply-secrets-with-gh.sh to upload to GitHub secrets.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="${1:-$SCRIPT_DIR/cdn-secrets.env}"

# ── Preflight checks ─────────────────────────────────────────────────────────

for cmd in terraform aws; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Error: $cmd is not installed." >&2
    exit 1
  fi
done

# ── Install Lambda dependencies if needed ─────────────────────────────────────

LAMBDA_DIR="$INFRA_DIR/lambda/presign"
if [[ ! -d "$LAMBDA_DIR/node_modules" ]]; then
  echo "Installing Lambda dependencies..."
  (cd "$LAMBDA_DIR" && npm install --silent)
fi

# ── Terraform init + apply ────────────────────────────────────────────────────

cd "$INFRA_DIR"

if [[ ! -d ".terraform" ]]; then
  echo "Initializing Terraform..."
  terraform init
fi

echo ""
echo "Running terraform apply..."
terraform apply

# ── Extract outputs ───────────────────────────────────────────────────────────

CLOUDFRONT_DOMAIN="$(terraform output -raw cloudfront_domain)"
LAMBDA_PRESIGN_URL="$(terraform output -raw lambda_presign_url)"
S3_BUCKET_NAME="$(terraform output -raw s3_bucket_name)"
CLOUDFRONT_DIST_ID="$(terraform output -raw cloudfront_distribution_id)"

CDN_BASE_URL="https://$CLOUDFRONT_DOMAIN"

# ── Write secrets env file ────────────────────────────────────────────────────

cat > "$OUTPUT_FILE" <<EOF
# Spot CDN secrets — generated by 01-terraform-apply-and-export.sh
# $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# Feed to: scripts/apply-secrets-with-gh.sh $OUTPUT_FILE
CDN_BASE_URL=$CDN_BASE_URL
CDN_PRESIGN_URL=$LAMBDA_PRESIGN_URL
CDN_S3_BUCKET=$S3_BUCKET_NAME
CDN_CLOUDFRONT_ID=$CLOUDFRONT_DIST_ID
EOF

echo ""
echo "Terraform outputs exported to: $OUTPUT_FILE"
echo ""
echo "  CDN_BASE_URL      = $CDN_BASE_URL"
echo "  CDN_PRESIGN_URL   = $LAMBDA_PRESIGN_URL"
echo "  CDN_S3_BUCKET     = $S3_BUCKET_NAME"
echo "  CDN_CLOUDFRONT_ID = $CLOUDFRONT_DIST_ID"
echo ""
echo "Next: upload to GitHub secrets with:"
echo "  scripts/apply-secrets-with-gh.sh $OUTPUT_FILE"
